local Anim = require("utils.animator")
local CFG = require("data.config.animations")

function init(self)
	msg.post(".", "acquire_input_focus")

	self.buttons = Anim.register_buttons({
		{ node = "btn_select", anim = CFG.btn_mode, action = function() msg.post("/main", "start_game", { mode = "classic" }) end },
	})
end

function on_message(self, message_id, message, sender)
	if message_id == hash("reset_ui") then
		Anim.reset_buttons(self.buttons)
	end
end

function on_input(self, action_id, action)
	return Anim.handle_buttons(self.buttons, action_id, action)
end