local ScreenManager = require("libs.screen_manager")
local BoardView = require("game.view.board_view")
local Selection = require("game.shikaku.selection")
local Input = require("game.shikaku.input")
local Solver = require("game.shikaku.solver")
local Board = require("game.shikaku.board")
local Levels = require("game.shikaku.levels.levels")

function init(self)
	msg.post(".", "acquire_input_focus")
	
	self.screens = ScreenManager.new()
	self.screens:register("menu", "/menu")
	self.screens:register("game", "/game")
	
	self.screens:go_to("menu")
end

function load_puzzle(self, category)
	if self.board_view then
		self.board_view:Clear()
	end

	local puzzle = Levels.load(category)
	if not puzzle then return end

	self.board = Board.new(puzzle.width, puzzle.height)
	for y = 1, puzzle.height do
		for x = 1, puzzle.width do
			local n = puzzle.data[y][x]
			if n and n ~= 0 then
				self.board:GetCell(x, y):SetNumber(n)
			end
		end
	end

	self.board_view = BoardView.new("/Factories#cellfactory", {
		cell_size = 64,
		spacing = 32,
		start_position = vmath.vector3(100, 300, 0)
	})
	self.board_view:Create(self.board)

	self.selection = Selection.new(self.board)
	self.input = Input.new(self.selection, self.board_view)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start_game") then
		self.screens:go_to("game")
		load_puzzle(self, message.category or "easy")
		msg.post(".", "acquire_input_focus") 

	elseif message_id == hash("back_to_menu") then
		-- Чистим игру
		if self.board_view then self.board_view:Clear() end
		self.board = nil
		self.input = nil
		self.selection = nil
		self.board_view = nil
		
		self.screens:go_to("menu")
		msg.post("/menu", "acquire_input_focus") 

	elseif message_id == hash("open_settings") then
		self.screens:push("settings")
	end
end

function on_input(self, action_id, action)
	-- Работает только когда активен экран "game"
	if self.screens:get_active() ~= "game" or not self.input then
		return
	end

	if action_id == hash("touch") then
		if action.pressed then
			self.input:MousePressed(action.x, action.y)
		elseif action.released then
			self.input:MouseReleased(action.x, action.y)

			if self.board:IsFull() then
				local rectangles = self.board:GetAllRectangles()
				if Solver.Check(self.board, rectangles) then
					print("SOLVED!")
					load_puzzle(self, "easy") -- следующий уровень
				else
					print("WRONG!")
				end
			end
		end
	end

	if action.x and action.y then
		self.input:MouseMoved(action.x, action.y)
	end
end