embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"test2_selection_bg\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 16.0\n"
  "  y: 16.0\n"
  "  z: 16.0\n"
  "  w: 16.0\n"
  "}\n"
  "size {\n"
  "  x: 64.0\n"
  "  y: 64.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "offset: 1.0\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlas/game.atlas\"\n"
  "}\n"
  ""
}
